# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (Production) Build and deploy container app to Azure Web App - acuello-cicd-challenge

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    DB_SERVER: '${{ secrets.DB_SERVER }}'
    DB_PORT: '${{ secrets.DB_PORT }}'
    DB_NAME: '${{ secrets.DB_NAME }}'
    DB_UID: '${{ secrets.DB_UID }}'
    DB_PASS: '${{ secrets.DB_PASS }}'
    JWT_SECRET: '${{ secrets.JWT_SECRET }}'
    OPENAI_TYPE: '${{ secrets.OPENAI_TYPE }}'
    OPENAI_VERSION: '${{ secrets.OPENAI_VERSION }}'
    OPENAI_KEY: '${{ secrets.OPENAI_KEY }}'
    OPENAI_BASE: '${{ secrets.OPENAI_BASE }}'
    OPENAI_ENGINE: '${{ secrets.OPENAI_ENGINE }}'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mcr.microsoft.com/
          username: ${{ secrets.AzureAppService_ContainerUsername_34694bc0eac347db819c5977091c8de8 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_5fc093f1000647f983c7fdff06d2eafb }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_34694bc0eac347db819c5977091c8de8 }}/appsvc/staticsite:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'acuello-cicd-challenge'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_a32878cba36e465ba4b1ca57bfd02e1d }}
            images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_34694bc0eac347db819c5977091c8de8 }}/appsvc/staticsite:${{ github.sha }}'